### PR TITLE
Fix syntetic event order

### PR DESCRIPTION
**Pull request by rti**
This patch addresses an issue with Gnome/X11 focus handling.

Given Gnomes "Pointer Location - press CTRL to highlight the pointer"
feature is enabled, Gnome will unfocus and refocus the currently active
window whenever CTRL is pressed, e.g. when issuing a CTRL-s. When the
window is refocussed, the keys CTRL and s are reported as pressed, so
winit can report them as synthetic key events. In order to report a
proper CTRL key combination to the app though, winit needs to first
report any modifier keys (in this case CTRL) and afterwards any other
keys. This patch ensures the proper order while reporting synthetic key
events.

This depends on #1.

Aims to fix https://github.com/neovide/neovide/issues/951

- [X] Tested on all platforms changed
- [X] Compilation warnings were addressed
- [X] `cargo fmt` has been run on this branch
- [X] `cargo doc` builds successfully
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality
- [ ] Updated [feature matrix](https://github.com/rust-windowing/winit/blob/master/FEATURES.md), if new features were added or implemented

### CODE REVIEW

**Comment by maroider** [comment]
This doesn't appear to introduce any problems on its own, but #1 appears to have introduced an issue where winit emits incorrect `ModifiersChanged` events. If I press and hold one or more modifier keys and then move the shift the focus around by moving the mouse between windows, winit will fail to emit `ModifiersChanged` for one or more of the modifiers once the focus is moved back to winit's window.

**Comment by rti** [comment]
To be honest, I moved along several month ago and won't allocate the resources to further look into this at the moment. Thanks a lot for all your work on this.

**Comment by maroider** [comment]
> To be honest, I moved along several month ago and won't allocate the resources to further look into this at the moment.

I don't blame you at all. This is not fun to work on.

**Comment by rti** [comment]
In order to clean up my github todo lists, I'll close this pr for now. Feel free to reopen/reassign/whatever you want to do with it though :)

**Pull request closed without merging**
